/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialsDocIdRouteImport } from './routes/materials.$docId'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated.categories.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedResultAttemptIdRouteImport } from './routes/_authenticated.result.$attemptId'
import { Route as AuthenticatedQuizzesQuizIdRouteImport } from './routes/_authenticated.quizzes.$quizId'
import { Route as AuthenticatedCategoriesSlugRouteImport } from './routes/_authenticated.categories.$slug'
import { Route as AuthenticatedAttemptAttemptIdRouteImport } from './routes/_authenticated.attempt.$attemptId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminQuizzesRouteImport } from './routes/_authenticated.admin.quizzes'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated.admin.questions'
import { Route as AuthenticatedAdminMaterialsRouteImport } from './routes/_authenticated.admin.materials'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated.admin.homepage'
import { Route as AuthenticatedAdminGenerateRouteImport } from './routes/_authenticated.admin.generate'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated.admin.documents'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated.admin.categories'
import { Route as AuthenticatedAdminSyllabusDocIdRouteImport } from './routes/_authenticated.admin.syllabus.$docId'

const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsDocIdRoute = MaterialsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => MaterialsRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedResultAttemptIdRoute =
  AuthenticatedResultAttemptIdRouteImport.update({
    id: '/result/$attemptId',
    path: '/result/$attemptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuizzesQuizIdRoute =
  AuthenticatedQuizzesQuizIdRouteImport.update({
    id: '/quizzes/$quizId',
    path: '/quizzes/$quizId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCategoriesSlugRoute =
  AuthenticatedCategoriesSlugRouteImport.update({
    id: '/categories/$slug',
    path: '/categories/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttemptAttemptIdRoute =
  AuthenticatedAttemptAttemptIdRouteImport.update({
    id: '/attempt/$attemptId',
    path: '/attempt/$attemptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminQuizzesRoute =
  AuthenticatedAdminQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMaterialsRoute =
  AuthenticatedAdminMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGenerateRoute =
  AuthenticatedAdminGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSyllabusDocIdRoute =
  AuthenticatedAdminSyllabusDocIdRouteImport.update({
    id: '/syllabus/$docId',
    path: '/syllabus/$docId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exams': typeof ExamsRoute
  '/materials': typeof MaterialsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/materials/$docId': typeof MaterialsDocIdRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/categories/$slug': typeof AuthenticatedCategoriesSlugRoute
  '/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/admin/syllabus/$docId': typeof AuthenticatedAdminSyllabusDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exams': typeof ExamsRoute
  '/materials': typeof MaterialsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/materials/$docId': typeof MaterialsDocIdRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/categories/$slug': typeof AuthenticatedCategoriesSlugRoute
  '/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/admin/syllabus/$docId': typeof AuthenticatedAdminSyllabusDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/exams': typeof ExamsRoute
  '/materials': typeof MaterialsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/materials/$docId': typeof MaterialsDocIdRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/quizzes': typeof AuthenticatedAdminQuizzesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/_authenticated/categories/$slug': typeof AuthenticatedCategoriesSlugRoute
  '/_authenticated/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/_authenticated/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/admin/syllabus/$docId': typeof AuthenticatedAdminSyllabusDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/exams'
    | '/materials'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/materials/$docId'
    | '/admin/categories'
    | '/admin/documents'
    | '/admin/generate'
    | '/admin/homepage'
    | '/admin/materials'
    | '/admin/questions'
    | '/admin/quizzes'
    | '/admin/users'
    | '/attempt/$attemptId'
    | '/categories/$slug'
    | '/quizzes/$quizId'
    | '/result/$attemptId'
    | '/admin/'
    | '/categories/'
    | '/admin/syllabus/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/exams'
    | '/materials'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/materials/$docId'
    | '/admin/categories'
    | '/admin/documents'
    | '/admin/generate'
    | '/admin/homepage'
    | '/admin/materials'
    | '/admin/questions'
    | '/admin/quizzes'
    | '/admin/users'
    | '/attempt/$attemptId'
    | '/categories/$slug'
    | '/quizzes/$quizId'
    | '/result/$attemptId'
    | '/admin'
    | '/categories'
    | '/admin/syllabus/$docId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/exams'
    | '/materials'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/profile'
    | '/materials/$docId'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/generate'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/materials'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/quizzes'
    | '/_authenticated/admin/users'
    | '/_authenticated/attempt/$attemptId'
    | '/_authenticated/categories/$slug'
    | '/_authenticated/quizzes/$quizId'
    | '/_authenticated/result/$attemptId'
    | '/_authenticated/admin/'
    | '/_authenticated/categories/'
    | '/_authenticated/admin/syllabus/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExamsRoute: typeof ExamsRoute
  MaterialsRoute: typeof MaterialsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$docId': {
      id: '/materials/$docId'
      path: '/$docId'
      fullPath: '/materials/$docId'
      preLoaderRoute: typeof MaterialsDocIdRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/result/$attemptId': {
      id: '/_authenticated/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quizzes/$quizId': {
      id: '/_authenticated/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizzesQuizIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories/$slug': {
      id: '/_authenticated/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof AuthenticatedCategoriesSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attempt/$attemptId': {
      id: '/_authenticated/attempt/$attemptId'
      path: '/attempt/$attemptId'
      fullPath: '/attempt/$attemptId'
      preLoaderRoute: typeof AuthenticatedAttemptAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quizzes': {
      id: '/_authenticated/admin/quizzes'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/materials': {
      id: '/_authenticated/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AuthenticatedAdminMaterialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/generate': {
      id: '/_authenticated/admin/generate'
      path: '/generate'
      fullPath: '/admin/generate'
      preLoaderRoute: typeof AuthenticatedAdminGenerateRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/syllabus/$docId': {
      id: '/_authenticated/admin/syllabus/$docId'
      path: '/syllabus/$docId'
      fullPath: '/admin/syllabus/$docId'
      preLoaderRoute: typeof AuthenticatedAdminSyllabusDocIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminGenerateRoute: typeof AuthenticatedAdminGenerateRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminMaterialsRoute: typeof AuthenticatedAdminMaterialsRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminQuizzesRoute: typeof AuthenticatedAdminQuizzesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminSyllabusDocIdRoute: typeof AuthenticatedAdminSyllabusDocIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminGenerateRoute: AuthenticatedAdminGenerateRoute,
  AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
  AuthenticatedAdminMaterialsRoute: AuthenticatedAdminMaterialsRoute,
  AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
  AuthenticatedAdminQuizzesRoute: AuthenticatedAdminQuizzesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminSyllabusDocIdRoute: AuthenticatedAdminSyllabusDocIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAttemptAttemptIdRoute: typeof AuthenticatedAttemptAttemptIdRoute
  AuthenticatedCategoriesSlugRoute: typeof AuthenticatedCategoriesSlugRoute
  AuthenticatedQuizzesQuizIdRoute: typeof AuthenticatedQuizzesQuizIdRoute
  AuthenticatedResultAttemptIdRoute: typeof AuthenticatedResultAttemptIdRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAttemptAttemptIdRoute: AuthenticatedAttemptAttemptIdRoute,
  AuthenticatedCategoriesSlugRoute: AuthenticatedCategoriesSlugRoute,
  AuthenticatedQuizzesQuizIdRoute: AuthenticatedQuizzesQuizIdRoute,
  AuthenticatedResultAttemptIdRoute: AuthenticatedResultAttemptIdRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface MaterialsRouteChildren {
  MaterialsDocIdRoute: typeof MaterialsDocIdRoute
}

const MaterialsRouteChildren: MaterialsRouteChildren = {
  MaterialsDocIdRoute: MaterialsDocIdRoute,
}

const MaterialsRouteWithChildren = MaterialsRoute._addFileChildren(
  MaterialsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ExamsRoute: ExamsRoute,
  MaterialsRoute: MaterialsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
